### PR TITLE
Adding my API key to prevent error.

### PR DESCRIPTION
**Pull request by fsargent**
Contact me if any changes are needed. The key is scope restricted to earlyoakland and github so we shouldn't go over the rate limit.

### CODE REVIEW

**Comment by tdooner** [comment]
Hello! Who is currently maintaining this project? Are you? I haven't heard anything about this project come up in OpenOakland in a long time.

If this project is unmaintained, would you like to be added as a collaborator?

**Comment by fsargent** [comment]
No idea who's maintaining it. I saw it in passing and reference it from time to time. I saw that someone recently committed to it, and moved it from earlyoakland.org to earlyoakland.com - not sure why. 
I don't mind being a maintainer for this. I'm out in New York these days though.

**Comment by spjika** [comment]
I've not maintained for some time no. Happy to help get it current if
others have interest

Spike
www.stealingbeautyphotography.com

**Comment by tdooner** [comment]
@fsargent Hearing no objection, I've made you a collaborator on this repo. The change here looks good to me, so feel free to merge it. I'm not sure how we deploy to this site. Do you know? If there is anything I can help you with for that purpose let me know.

Also, if you are still in Oakland, it would be great to meet you at a hack night sometime!

**Comment by spjika** [comment]
site is served from here on gh-pages branch

Spike
www.stealingbeautyphotography.com

**Comment by fsargent** [comment]
@tdooner I don't have write access still it appears. Can't merge without it.

**Comment by tdooner** [comment]
@fsargent It says you haven't accepted the collaborator invite link yet. Try going here:
https://github.com/openoakland/EarlyOakland/invitations

**Comment by fsargent** [comment]
Done and fixed.

**Pull request merged**
